###################################################
### GET GAMES #####################################
###################################################
GET http://localhost:5000/games/7

###################################################
### RUN GAME ######################################
###################################################
POST http://localhost:5000/games/7

###################################################
### DELETE GAMES ##################################
###################################################
DELETE http://localhost:5000/games/7