###################################################
### GET GAMES #####################################
###################################################
GET http://localhost:5000/games/1

###################################################
### RUN GAME ######################################
###################################################
POST http://localhost:5000/games/1

###################################################
### DELETE GAMES ##################################
###################################################
DELETE http://localhost:5000/games/1
Authorization: Bearer ___PUT_YOUR_TOKEN_HERE___