###################################################
### GET PLAYERS ###################################
###################################################
GET http://localhost:5000/players

###################################################
### ADD PLAYER ####################################
###################################################
POST http://localhost:5000/players
Content-Type: application/json

{
    "username": "victor"
}

###################################################
### ADD ANONIM ####################################
###################################################
POST http://localhost:5000/players


###################################################
### MODIFY PLAYER #################################
###################################################
PUT http://localhost:5000/players/1
Content-Type: application/json

{
    "username": "javi"
}

###################################################
### DELETE PLAYER #################################
###################################################
DELETE http://localhost:5000/players/3


