###################################################
### GET RANKING ###################################
###################################################
GET http://localhost:5000/ranking

###################################################
### GET WINNER ####################################
###################################################
GET http://localhost:5000/ranking/winner

###################################################
### GET LOSER #####################################
###################################################
GET http://localhost:5000/ranking/loser